---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ .Values.service.name }}
