# Default values for voice-over.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: voice-over

deployment:
  name: voice-over
  replicaCount: 1
  image:


service:
  name: voice-over
  type: ClusterIP
  port: 3000

ingress:
  name: voice-over-ingress
  className: nginx
  hosts:
    host: gol.com
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  name: voice-over
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


affinity: {}